name: distribuidora_movil
description: App móvil profesional para gestión de distribuidora mayorista.
publish_to: none
version: 0.2.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  go_router: ^14.6.2
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  geolocator: ^12.0.0
  mobile_scanner: ^5.2.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
